"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Check, ChevronDown, Menu, MessageCircle, Phone, X } from "lucide-react";

export const phone="+225 0506656210";
export const whatsapp="https://wa.me/2250506656210";
const inventoryData=[
 {slug:"villa-moderne",title:"Villa moderne avec jardin",location:"Cocody, Abidjan",type:"Villa",image:"/bien-villas-modernes.jpg",tag:"À vendre",description:"Une villa contemporaine lumineuse, pensée pour une vie familiale confortable et élégante."},
 {slug:"residence-neuilly",title:"Résidence Neuilly",location:"Deux-Plateaux, Abidjan",type:"Appartement",image:"/bien-residence-neuilly.jpg",tag:"À vendre",description:"Une résidence urbaine avec balcons et accès sécurisé, idéale pour investir."},
 {slug:"duplex-modernes",title:"Villas duplex modernes",location:"Riviera, Abidjan",type:"Villa",image:"/bien-villas-duplex-modernes.jpg",tag:"À vendre",description:"Des duplex aux lignes épurées dans un environnement résidentiel serein."},
 {slug:"villa-familiale",title:"Villa familiale arborée",location:"Marcory, Abidjan",type:"Maison",image:"/bien-villa-familiale.jpg",tag:"À vendre",description:"Une adresse spacieuse avec jardin et belle présence depuis la rue."},
 {slug:"immeuble-urbain",title:"Immeuble urbain",location:"Plateau, Abidjan",type:"Immeuble",image:"/bien-immeuble.jpg",tag:"Opportunité",description:"Un actif immobilier à fort potentiel au cœur d'un quartier stratégique."}
];
const serviceList=[
 {title:"Vente & achat",text:"Des biens sélectionnés et un accompagnement clair à chaque étape.",href:"/services/transaction",icon:"⌂"},
 {title:"Gestion locative",text:"Confiez vos biens à une équipe attentive, rigoureuse et disponible.",href:"/services/gestion-locative",icon:"▦"},
 {title:"Conseil immobilier",text:"Valorisation, stratégie et décisions éclairées pour vos projets.",href:"/services/conseil",icon:"◈"},
];
export function getInventory(){ return inventoryData; }
export function getServiceList(){ return serviceList; }
export function Header(){const [open,setOpen]=useState(false);return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="container-shell flex h-20 items-center justify-between gap-6"><Link href="/" className="flex items-center gap-3"><Image src="/logo-ballal.jpg" alt="Ballal Group SARL" width={66} height={66} className="h-14 w-14 rounded-full object-cover"/><span className="hidden font-display text-sm font-bold tracking-[.08em] text-navy sm:block">BALLAL-GROUP <span className="text-orange">SARL</span><small className="block text-[9px] tracking-[.25em] text-green">BALLAL IMMOBILIER</small></span></Link><nav className="hidden items-center gap-7 text-sm font-semibold text-slate-600 lg:flex"><Link className="hover:text-orange" href="/">Accueil</Link><Link className="hover:text-orange" href="/catalogue">Nos biens</Link><Link className="hover:text-orange" href="/services/transaction">Services</Link><Link className="hover:text-orange" href="/a-propos">À propos</Link><Link className="hover:text-orange" href="/contact">Contact</Link></nav><div className="hidden items-center gap-3 sm:flex"><a href={`tel:${phone.replaceAll(" ","")}`} className="flex items-center gap-2 text-sm font-bold text-navy"><Phone size={16}/>Appeler</a><Link href="/contact" className="rounded-full bg-orange px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-orange/90">Parlons de votre projet</Link></div><button aria-label="Ouvrir le menu" className="rounded-lg p-2 text-navy lg:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="container-shell flex flex-col gap-4 border-t border-slate-100 py-5 text-sm font-semibold lg:hidden"><Link href="/" onClick={()=>setOpen(false)}>Accueil</Link><Link href="/catalogue" onClick={()=>setOpen(false)}>Nos biens</Link><Link href="/services/transaction" onClick={()=>setOpen(false)}>Services</Link><Link href="/a-propos" onClick={()=>setOpen(false)}>À propos</Link><Link href="/contact" onClick={()=>setOpen(false)}>Contact</Link></nav>}</header>}
export function Footer(){return <footer className="bg-navy-deep py-12 text-white"><div className="container-shell grid gap-10 md:grid-cols-[1.3fr_1fr_1fr]"><div><Image src="/logo-ballal.jpg" alt="Ballal Group" width={80} height={80} className="mb-5 rounded-full"/><p className="max-w-sm text-sm leading-6 text-slate-300">Votre partenaire de confiance pour des transactions immobilières sereines à Abidjan.</p></div><div><h3 className="mb-4 font-display font-bold text-orange">Navigation</h3><div className="grid gap-3 text-sm text-slate-300"><Link href="/catalogue">Nos biens</Link><Link href="/a-propos">À propos</Link><Link href="/contact">Contact</Link></div></div><div><h3 className="mb-4 font-display font-bold text-orange">Nous joindre</h3><p className="text-sm leading-7 text-slate-300">Plateau Dokui, Olympe<br/>Abidjan, Côte d'Ivoire<br/>{phone}</p></div></div><div className="container-shell mt-10 border-t border-white/15 pt-5 text-xs text-slate-400">© 2026 Ballal-Group SARL · Expertise · Confiance · Excellence</div></footer>}
export function WhatsApp(){return <a href={whatsapp} target="_blank" rel="noreferrer" aria-label="Contacter Ballal sur WhatsApp" className="fixed bottom-5 right-5 z-40 flex items-center gap-2 rounded-full bg-green px-4 py-3 text-sm font-bold text-white shadow-xl transition hover:-translate-y-1"><MessageCircle size={18}/>WhatsApp</a>}
export function SectionTitle({eyebrow,title,children}:{eyebrow:string;title:string;children?:React.ReactNode}){return <div className="mb-10 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.25em] text-orange">{eyebrow}</p><h2 className="font-display text-3xl font-bold tracking-tight text-navy md:text-4xl">{title}</h2></div>{children}</div>}
export function PropertyCard({p}:{p:ReturnType<typeof getInventory>[number]}){return <Link href={`/catalogue/${p.slug}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden"><Image src={p.image} alt={p.title} fill className="object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-3 top-3 rounded-full bg-white px-3 py-1 text-xs font-bold text-green">{p.tag}</span></div><div className="p-5"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-orange">{p.type}</p><h3 className="font-display text-lg font-bold text-navy">{p.title}</h3><p className="mt-2 text-sm text-slate-500">{p.location}</p><span className="mt-5 flex items-center gap-2 text-sm font-bold text-green">Découvrir <ArrowRight size={16}/></span></div></Link>}
export function ServiceCard({s}:{s:ReturnType<typeof getServiceList>[number]}){return <Link href={s.href} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:border-orange hover:shadow-lg"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-navy text-2xl text-white">{s.icon}</div><h3 className="font-display text-xl font-bold text-navy">{s.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{s.text}</p><span className="mt-5 flex items-center gap-2 text-sm font-bold text-orange">En savoir plus <ArrowRight size={16}/></span></Link>}
export function Checklist({items}:{items:string[]}){return <ul className="grid gap-4">{items.map(i=><li key={i} className="flex gap-3 text-slate-600"><Check className="mt-1 shrink-0 text-green" size={18}/>{i}</li>)}</ul>}
